### ISSUE TITLE
Is this a rewrite of jscpd?

### ISSUE THREAD

**Issue by esmiralha** [kucherenko/basta#2]
Last commit was in 2017. Any plans to keep improving it? Need help?

**Comment by kucherenko** [comment]
The repo is a lab, I'm working on a new version of jscpd based on experiences what I got here. But you can install and use basta as well.
Also, I'm going to the highlight alpha version of jscpd. You can try to install `npm i jscpd@1.0.0-alpha.2` and get more than 70 new languages to support and other new functionality.
All source located in jscpd repo in the alpha branch.
BIG THANK YOU for help suggestion. If you feel the power and have the time it would be great!
